motosaurio/cart/urls.py
from django.urls import path
from . import views
app_name = 'cesta'

urlpatterns = [
 path('', views.cesta_detail, name='cesta_detail'),
 path('add/<int:product_id>/', views.cesta_add, name='cesta_add'),
 path('remove/<int:product_id>/', views.cesta_remove, 
 name='cesta_remove'),
]

motosaurio/motosaurio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path('cesta/', include('cart.urls', namespace='cesta')),
    path('reclamaciones/', include('reclamaciones.urls', namespace='reclamaciones')),
    path('empresa/', include('empresa.urls', namespace='empresa')),
    path("order/", include("order.urls", namespace="order")),
    path("shop/", include("shop.urls", namespace="shop"))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

motosaurio/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
 path('', views.CheckoutOrder.as_view(), name='checkout'),
 path('<int:order_id>/stripe', views.StripeCheckout.as_view(), name='stripe_checkout'),
 path('my_orders/', views.ListOrdersUser.as_view(), name="list-orders-user"),
 path('tracking', views.Tracking.as_view(), name = 'tracking'),
 path('tracking/<int:order_id>', views.TrackingShow.as_view(), name='tracking_show')
]

motosaurio/shop/urls.py
from django.urls import path
from .views import ListProducts, ProductDetailView, sold_products_view

app_name = 'shop'

urlpatterns = [
    path('', ListProducts.as_view(), name='dashboard'),
    path('products_sold/', sold_products_view, name='productos_vendidos'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

motosaurio/cart/models.py
from django.db import models

# Create your models here.

motosaurio/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cesta import Cesta
from .forms import CestaAddProductForm
from django.shortcuts import render, redirect

@require_POST
def cesta_add(request, product_id):
    cesta = Cesta(request)
    product = get_object_or_404(Product, id=product_id)
    form = CestaAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cesta.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cesta:cesta_detail')

@require_POST
def cesta_remove(request, product_id):
    cesta = Cesta(request)
    product = get_object_or_404(Product, id=product_id)
    cesta.remove(product)
    return redirect('cesta:cesta_detail')

def cesta_detail(request):
 cesta = Cesta(request)
 for item in cesta:
    item['update_quantity_form'] = CestaAddProductForm(initial={
                                    'quantity': item['quantity'],
                                    'override': True})
 return render(request, 'cesta/detail.html', {'cesta': cesta})

motosaurio/cart/templates/cesta/detail.html
{% extends "account/dashboard.html" %}
{% load static %}
{% load custom_tags %}

{% block title %}
 Tu cesta de la compra
{% endblock %}

{% block content %}
    <table class="cesta">
        <thead>
        <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Eliminar</th>
            <th>Precio unitario</th>
            <th>Precio</th>
        </tr>
        </thead>
        <tbody>
            {% for item in cesta %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                {% if product.image %}
                                    {% with new_url=product.image.url|cambia_url:"/shop" %}
                                    <img src="{{ new_url }}" class="card-img-top product-img" alt="Product image" width="100" height="100">
                                    {% endwith %}
                                {% else %}
                                    <img src="{% static 'images/Imagen_no_disponible.png' %}" alt="Imagen no disponible" width="100" height="100">
                                {% endif %}
                            </a>
                        </td>

                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cesta:cesta_add" product.id %}" method="post">
                                 {{ item.update_quantity_form.quantity }}
                                 {{ item.update_quantity_form.override }}
                                 <input type="submit" value="Actualizar">
                                 {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cesta:cesta_remove" product.id %}" 
                            method="post">
                                <input type="submit" value="Remove">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cesta.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:dashboard' %}" class="button
        light">Continúa comprando</a>
        <a href="{% url 'order:checkout' %}" class="button">Pagar</a>
    </p>

    <script>
        function aumentarCantidad(cantidad_id) {
            var cantidad = document.getElementById(cantidad_id);
            cantidad.stepUp();
        }
      
        function disminuirCantidad(cantidad_id) {
            var cantidad = document.getElementById(cantidad_id);
            cantidad.stepDown();
        }
    </script>
{% endblock %}