motosaurio/cart/urls.py
from django.urls import path
from . import views
app_name = 'cesta'

urlpatterns = [
 path('', views.cesta_detail, name='cesta_detail'),
 path('add/<int:product_id>/', views.cesta_add, name='cesta_add'),
 path('remove/<int:product_id>/', views.cesta_remove, 
 name='cesta_remove'),
]

motosaurio/motosaurio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path('cesta/', include('cart.urls', namespace='cesta')),
    path('reclamaciones/', include('reclamaciones.urls', namespace='reclamaciones')),
    path('empresa/', include('empresa.urls', namespace='empresa')),
    path("order/", include("order.urls", namespace="order")),
    path("shop/", include("shop.urls", namespace="shop"))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

motosaurio/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
 path('', views.CheckoutOrder.as_view(), name='checkout'),
 path('<int:order_id>/stripe', views.StripeCheckout.as_view(), name='stripe_checkout'),
 path('my_orders/', views.ListOrdersUser.as_view(), name="list-orders-user"),
 path('tracking', views.Tracking.as_view(), name = 'tracking'),
 path('tracking/<int:order_id>', views.TrackingShow.as_view(), name='tracking_show')
]

motosaurio/order/models.py
from django.db import models

from shop.models import Product
from motosaurio.models import MiUsuario
from datetime import date

# Create your models here.

class Order(models.Model):

    tipos_pago = [
        ["Cr", "Contrareembolso"],
        ["T", "Tarjeta"]
    ]

    tipos_envio = [
        ["D", "A domicilio"],
        ["R", "Recoger en tienda"]
    ]

    estados = [
        ['P','Procesando'], 
        ['A','Aceptado'], 
        ['E','Enviado'], 
        ['EN','Entregado']
    ]

    customer = models.ForeignKey(MiUsuario, null=True, on_delete=models.SET_NULL)
    first_name = models.CharField('Nombre', max_length=200)
    email = models.EmailField('Correo elecrónico')
    direccion = models.CharField('Dirección', max_length=200)
    cod_postal = models.IntegerField('Código postal')
    tipo_pago = models.TextField("Tipo de pago", choices = tipos_pago)
    total_price = models.FloatField(default=0)
    delivery_type = models.TextField("Tipo de envio", choices = tipos_envio)
    estado = models.TextField("Estado", choices=estados, default=estados[0])
    fecha_creacion=models.DateField("Fecha de creación", default=date.today)

    @property
    def legible_estado(self):
        for tipo in self.estados:
            if tipo[0] == self.estado:
                return tipo[1]
        return None

    def __str__(self):
        return "Order " + str(self.id)
    
    @property
    def legible_tipo_pago(self):
        for tipo in self.tipos_pago:
            if tipo[0] == self.tipo_pago:
                return tipo[1]
        return None
    
    @property
    def legible_tipo_envio(self):
        for tipo in self.tipos_envio:
            if tipo[0] == self.delivery_type:
                return tipo[1]
        return None

class CartItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

motosaurio/order/forms.py
from django import forms
from django.core.exceptions import ValidationError

class OrderForm(forms.Form):
    tipos_pago = [
        ["Cr", "Contrareembolso"],
        ["T", "Tarjeta"]
    ]

    tipos_envio = [
        ["D", "A domicilio"],
        ["R", "Recoger en tienda"]
    ]

    first_name = forms.CharField()
    email = forms.EmailField()
    direction = forms.CharField()
    postal_code = forms.IntegerField()
    payment_type = forms.ChoiceField(choices = tipos_pago, initial='T', help_text = "Método de pago")
    card_number = forms.CharField(max_length = 16, min_length = 16, required=False)
    delivery_type = forms.ChoiceField(choices = tipos_envio, initial = "D", help_text = "Método de envío")

motosaurio/order/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.conf import settings
from django.db import transaction
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseNotFound

from motosaurio.models import MiUsuario
from cart.cesta import Cesta
from shop.models import Product

from .forms import OrderForm
from .models import Order, CartItem

import stripe
from decimal import Decimal

class CheckoutOrder(TemplateView):
    
    def get(self, request, *args, **kwargs):
        template_name = "checkout_order.html"
        context = {}
        
        order_created_id = request.session.get("order_created_id")
        if order_created_id:
            request.session["order_created_id"] = None
            request.session.modified = True
            try:
                Order.objects.get(id = order_created_id).delete()    
            except Order.DoesNotExist:
                pass

        form = OrderForm()

        if request.user.is_authenticated:
            user = request.user
            form["first_name"].initial = user.first_name
            form["email"].initial = user.email
            form["direction"].initial = user.direccion
            form["postal_code"].initial = user.codigo
            form["payment_type"].initial = user.payment_type
            form["delivery_type"].initial = user.delivery_type
        
        stripe.public_key = settings.STRIPE_PUBLIC_KEY

        context["stripe_public_key"] = stripe.public_key
        context["form"] = form
        cesta = Cesta(request)
        products = [i for i in cesta]
        total_price = cesta.get_total_price()
        # context["cesta"] = Cesta(request)
        context["products"] = products
        context["total_price"] = total_price

        return render(request, template_name = template_name, context = context)
    
    def post(self, request, *args, **kwargs):

        @transaction.atomic
        def create_order(user, form, cesta):
            delivery_type = form["delivery_type"]
            final_price = cesta.get_total_price()

            if final_price <= 30:
                if delivery_type.data == "D":
                    final_price += Decimal("4.99")
                elif delivery_type.data == "R":
                    final_price += Decimal("3.99")

            order = Order(customer = user, \
                          first_name = form["first_name"].data, \
                          email = form["email"].data, \
                          direccion = form["direction"].data, \
                          cod_postal = form["postal_code"].data, \
                          tipo_pago = form["payment_type"].data, \
                          total_price = final_price, \
                          delivery_type = delivery_type, \
                          estado = "P"
                        )
            order.save()

            for k,v in cesta.cesta.items():
                cart_item = CartItem(item = Product.objects.get(id = k), quantity = v["quantity"], order = order)
                cart_item.save()
            
            return order

        form = OrderForm(request.POST)
        cesta = Cesta(request)

        if form.is_valid():
            if request.user.is_authenticated:
                user = request.user
            else:
                user = None

            order_created_id = request.session.get("order_created_id")

            if order_created_id:
                try:
                    Order.objects.get(id = order_created_id).delete()
                except Order.DoesNotExist:
                    pass

            order = create_order(user, form, cesta)
            order_created_id = request.session["order_created_id"] = order.id
            request.session.modified = True

            if order.tipo_pago == "T":
                # Credit card
                # return redirect(f"/order/{order.id}/stripe")
                stripe.api_key = settings.STRIPE_SECRET_KEY
                token = request.POST.get('stripeToken')
                amount = order.total_price
                
                try:
                    # Create a charge using the token and amount
                    charge = stripe.Charge.create(
                        amount=int(amount*100), # From eur to cents
                        currency='eur',
                        source=token,
                        description=f'Cargo por el pedido con id {order.id}',
                    )

                    # Payment was successful
                    # Empty cart and send confirmation email
                    request.session["order_created_id"] = None
                    request.session[settings.CART_SESSION_ID] = None
                    request.session.modified = True

                    if(order.email != None):
                        send_confirmation_mail(order.first_name, order.email, order.id)

                    email = order.email
                    context = {"email": email}

                    return render(request, 'checkout_thanks.html', context)

                except stripe.error.CardError as e:
                    # Card was declined
                    error_message = str(e)

                    stripe.public_key = settings.STRIPE_PUBLIC_KEY

                    context = {
                        "stripe_public_key": stripe.public_key,
                        'error_message': error_message,
                        "form": form,
                        "cesta": cesta
                    }

                    order_created_id = request.session.get("order_created_id")
                    if order_created_id:
                        request.session["order_created_id"] = None
                        request.session.modified = True
                        try:
                            Order.objects.get(id = order_created_id).delete()    
                        except Order.DoesNotExist:
                            pass
                    
                    return render(request, "checkout_order.html", context)
            else:
                # Contrareembolso
                # Empty cart and send confirmation email
                request.session["order_created_id"] = None
                request.session[settings.CART_SESSION_ID] = None
                request.session.modified = True
                
                if(order.email != None):
                    send_confirmation_mail(order.first_name, order.email, order.id)

                return render(request, 'checkout_thanks.html', {"email":order.email})
        else:
            context = {}

            context["form"] = form

            stripe.public_key = settings.STRIPE_PUBLIC_KEY
            context["stripe_public_key"] = stripe.public_key
            
            cesta = Cesta(request)
            products = [i for i in cesta]
            total_price = cesta.get_total_price()
            context["products"] = products
            context["total_price"] = total_price
            return render(request, "checkout_order.html", context = context)
        
class StripeCheckout(TemplateView):

    def get(self, request, order_id, *args, **kwargs):
        stripe.public_key = settings.STRIPE_PUBLIC_KEY
        order = Order.objects.get(id = order_id)

        context = {
            "stripe_public_key": stripe.public_key,
            "final_price": order.total_price,
            "order_id": order.id
        }

        return render(request, "stripe_checkout.html", context)

    def post(self, request, order_id, *args, **kwargs):
        stripe.api_key = settings.STRIPE_SECRET_KEY
        token = request.POST.get('stripeToken')
        order =  Order.objects.get(id = order_id)
        amount = order.total_price
        email = order.email
        context = {"email":email}
        
        try:
            # Create a charge using the token and amount
            charge = stripe.Charge.create(
                amount=int(amount*100), # From eur to cents
                currency='eur',
                source=token,
                description=f'Cargo por el pedido con id {order.id}',
            )

            # Payment was successful
            # Empty cart and send confirmation email
            request.session["order_created_id"] = None
            request.session[settings.CART_SESSION_ID] = None
            request.session.modified = True

            if(order.email != None):
                send_confirmation_mail(order.first_name, order.email, order.id)

            return render(request, 'checkout_thanks.html', context)

        except stripe.error.CardError as e:
            # Card was declined
            error_message = str(e)

            stripe.public_key = settings.STRIPE_PUBLIC_KEY
            order = Order.objects.get(id = order_id)

            context = {
                "stripe_public_key": stripe.public_key,
                "final_price": order.total_price,
                "order_id": order.id,
                'error_message': error_message
            }
            
            return render(request, 'stripe_checkout.html', context)

@method_decorator(login_required(login_url='/account/login'), name='dispatch')
class ListOrdersUser(TemplateView):
    template_name = 'list_orders_user.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        orders = Order.objects.filter(customer = user)
        context["orders"] = list()

        for order in orders:
            context["orders"].append((order, list(CartItem.objects.filter(order = order))))

        return context
 
    
class Tracking(TemplateView):
    template_name = "tracking.html"
    
class TrackingShow(TemplateView):

    def get(self, request, order_id, *args, **kwargs):
        try:

motosaurio/order/templates/checkout_order.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %} Datos de envío y pago {% endblock %}
{% block extrahead %}
<style>
    .form-row-container {
        display: flex;
        flex-direction: column;
        margin-bottom: 1rem;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Left half of the screen - Cart -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Carrito
                </div>
                <div class="card-body">
                    <ul>
                        {% for item in products %}
                        <li> {{ item.quantity }} unidades: {{ item.product.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <!-- Right half of the screen - Buy Form and Price -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Datos de compra
                </div>
                <div class="card-body">
                    <form id="payment-form" style="overflow: hidden" method="post">
                        {% csrf_token %}

                        <h4> Datos del cliente </h4>
                        <div class="form-row-container">
                            <label for="{{ form.name.id_for_label }}">Nombre: </label>
                            <input type="text" class="form-control" name="first_name" id="{{ form.first_name.id_for_input }}" value="{{ form.first_name.data|default:form.first_name.initial }}" required>
                            {{ form.name.errors }}
                        </div>

                        <div class="form-row-container">
                            <label for="{{ form.email.id_for_label }}">Correo electrónico: </label>
                            <input type="email" class="form-control" name="email" maxlength="320" id="{{ form.email.id_for_label }}" value="{{ form.email.data|default:form.email.initial }}" required>
                            {{ form.email.errors }}
                        </div>

                        <div class="form-row-container">
                            <label for="{{ form.direction.id_for_label }}">Dirección: </label>
                            <input type="text" class="form-control" name="direction" id="{{ form.direction.id_for_label }}" value="{{ form.direction.data|default:form.direction.initial }}" required>
                            {{ form.direction.errors }}
                        </div>

                        <div class="form-row-container">
                            <label for="{{ form.postal_code.id_for_label }}">Código postal: </label>
                            <input type="number" class="form-control" name="postal_code" id="{{ form.postal_code.id_for_label }}" value="{{ form.postal_code.data|default:form.postal_code.initial }}" required>
                            {{ form.postal_code.errors }}
                        </div>

                        <!-- Payment method selector -->
                        <div class="form-row-container">
                            <h4> Datos de pago </h4>
                            <label for="{{ form.payment_type.id_for_label }}">Método de pago:</label>
                            <select class="form-control" id="{{ form.payment_type.id_for_label }}" name="payment_type">
                                <option value="T">Tarjeta</option>
                                <option value="Cr">Contrareembolso</option>
                            </select>
                            {{ form.payment_type.errors }}
                        </div>
                        
                        <div class="form-row-container">
                            <label> Tarjeta </label>
                        </div>

                        <div id="card-element" class="form-row-container"></div>
                        <div>{{ error_message }}</div>

                        <div class="form-row-container">
                            <h4> Forma de envío </h4>
                            <label for="{{ form.delivery_type.id_for_label }}">Forma de envío:</label>
                            <select class="form-control" id="{{ form.delivery_type.id_for_label }}" name="delivery_type">
                                <option value="D">A domicilio</option>
                                <option value="R">Recoger en tienda</option>
                            </select>
                            {{ form.delivery_type.errors }}
                        </div>

                        <div class="form-row-container">
                            <h5> Precios de envío </h5>
                            <span>A domicilio: 4,99 €</span>
                            <span>Recoger en tienda: 3,99€</span>
                            <span>Pedidos de más de 30€: Gratis</span>
                        </div>  

                        <!-- Price and Buy Button -->
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="price">Price:</label>
                                <p id="price">{{ total_price|floatformat:"2" }} €</p>
                            </div>
                            <div class="col-md-6 text-right">
                                <button type="submit" class="btn btn-success">Buy</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% if form.payment_type.data == None and form.payment_type.initial == 'Cr' %}
<script>
    document.getElementById("{{ form.payment_type.id_for_label }}").selectedIndex = 1;
</script>
{% endif %}

{% if form.payment_type.data == 'Cr' %}
<script>
    document.getElementById("{{ form.payment_type.id_for_label }}").selectedIndex = 1;
</script>
{% endif %}

{% if form.delivery_type.data == None and form.delivery_type.initial == 'R' %}
<script>
    document.getElementById("{{ form.delivery_type.id_for_label }}").selectedIndex = 1;
</script>
{% endif %}

{% if form.delivery_type.data == 'R' %}
<script>
    document.getElementById("{{ form.delivery_type.id_for_label }}").selectedIndex = 1;
</script>
{% endif %}

<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe('{{ stripe_public_key }}');
    var elements = stripe.elements();

    var card = elements.create('card');
    card.mount('#card-element');

    var form = document.getElementById('payment-form');
    var payment_type_input = document.getElementById("{{ form.payment_type.id_for_label }}")

    form.addEventListener('submit', function (event) {
        event.preventDefault();

        if(payment_type_input.value == "T") {
            stripe.createToken(card).then(function (result) {
                if (result.error) {
                // Show error to the user
                console.error(result.error.message);
                } else {
                // Send the token to your server
                // You can use AJAX to send the token to your Django view
                console.log(result.token);

                // Append the token to the form before submitting
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'stripeToken');
                hiddenInput.setAttribute('value', result.token.id);
                form.appendChild(hiddenInput);

                // Submit the form
                form.submit();
                }
            });
        } else if(payment_type_input.value == "Cr") {
            form.submit();
        } else {
            console.error("The payment type value (" + payment_type_input.value + ") is invalid.")
        }
    });
</script>

<!-- Bootstrap JavaScript and dependencies (Popper.js and jQuery) -->
<script src="https://code.jquery.com/jquery-3.7.1.slim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

motosaurio/order/templates/checkout_thanks.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
    <br>
    <h1>¡Muchas gracias por su compra!</h1>
    {% if email != None %}
    <p>Se ha enviado un correo de confirmación a la dirección {{ email }}</p>
    {% endif %}
    <br>
{% endblock %}

motosaurio/order/templates/list_orders_user.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %} Datos de envío y pago {% endblock %}
{% block extrahead %}
<style>
    /* Custom CSS for adjusting height to content */
    .custom-container {
      display: flex;
      flex-direction: column;
      align-items: stretch;
    }

    .custom-row {
      display: flex;
      flex-wrap: wrap;
      margin-bottom: 10px;
    }

    .custom-col {
      flex: 1;
      margin-right: 10px; /* Adjust margin as needed */
    }

    /* Responsive adjustments */
    @media (max-width: 576px) {
      .custom-col {
        flex: 0 0 100%; /* Full width on small screens */
        margin-right: 0;
        margin-bottom: 10px;
      }
    }
  </style>
{% endblock %}

{% block content %}
<div class="container custom-container">
    {% for order_tuple in orders %}
    {% with order=order_tuple.0%}
    <div class="card" style="margin-bottom: 10px;">
        <div class="col custom-row">
            <div class="col custom-col">Id: {{ order.id }} | &nbsp; <a href="{% url 'order:tracking_show' order.id %}">Seguimiento del pedido</a></div>
        </div>
        <div class="col custom-row">
            <div class="col custom-col">Nombre: {{ order.first_name }} | &nbsp; Email: {{ order.email }}</div>
        </div>
        <div class="col custom-row">
            <div class="col custom-col">Direccion: {{ order.direction }} | &nbsp; Codigo postal: {{ order.cod_postal }} | &nbsp; Tipo de envío: {{ order.legible_tipo_envio }}</div>
        </div>
        <div class="col custom-row">
            <div class="col custom-col">Precio total: {{ order.total_price }} | &nbsp; Tipo de pago: {{ order.legible_tipo_pago }}</div>
        </div>
    

        <button class="btn btn-primary" data-toggle="collapse" data-target="#hiddenContainer-{{ order.id }}" aria-expanded="false" aria-controls="hiddenContainer">
            Mostrar productos
        </button>

        <div class="collapse" id="hiddenContainer-{{ order.id }}" style="margin-bottom: 10px;">
            {% with cart_items=order_tuple.1 %}
            {% for cart_item in cart_items %}
            <div class="card" style="margin-bottom: 10px;">
                <div class="col custom-row">
                    <div class="col custom-col">Nombre producto: {{ cart_item.item.name }}</div>
                </div>
                <div class="col custom-row">
                    <div class="col custom-col">Precio: {{ cart_item.item.price }} | &nbsp; Unidades: {{ cart_item.quantity }}</div>
                </div>
            </div>
            {% endfor %}
            {% endwith %}
        </div>
    </div>
    {% endwith %}
    {% endfor %}
</div>

<!-- Bootstrap JavaScript and dependencies (Popper.js and jQuery) -->
<script src="https://code.jquery.com/jquery-3.7.1.slim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

motosaurio/order/templates/stripe_checkout.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %} Stripe {% endblock %}

{% block content %}
  <script src="https://js.stripe.com/v3/"></script>

  <form action="{% url 'order:stripe_checkout' order_id %}" method="post" id="payment-form">
    {% csrf_token %}
    <!-- Display the order details and dynamically set the amount -->
    <p>Total del pedido: ${{ final_price }} €</p>

    <div id="card-element"></div>
    <button id="submit-button">Pagar</button>
  </form>

  <div>
      {{ error_message }}
  </div>

  <script>
    var stripe = Stripe('{{ stripe_public_key }}');
    var elements = stripe.elements();

    var card = elements.create('card');
    card.mount('#card-element');

    var form = document.getElementById('payment-form');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      stripe.createToken(card).then(function (result) {
        if (result.error) {
          // Show error to the user
          console.error(result.error.message);
        } else {
          // Send the token to your server
          // You can use AJAX to send the token to your Django view
          console.log(result.token);

          // Append the token to the form before submitting
          var hiddenInput = document.createElement('input');
          hiddenInput.setAttribute('type', 'hidden');
          hiddenInput.setAttribute('name', 'stripeToken');
          hiddenInput.setAttribute('value', result.token.id);
          form.appendChild(hiddenInput);

          // Submit the form
          form.submit();
        }
      });
    });
  </script>
{% endblock %}

motosaurio/order/templates/tracking.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %} Seguimiento {% endblock %}
{% block extrahead %}
<style>
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Introduzca el identificador de su pedido</h1>
    <input type="number" id="input" required>
    <button onclick="goToTracking()">Buscar</button>
</div>

<script>
    function goToTracking() {
        input = document.getElementById("input")
        window.location.href = "{% url 'order:tracking' %}" + "/" + input.value.toString()
    }
</script>

{% endblock %}

motosaurio/order/templates/tracking_show.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %} Datos de envío y pago {% endblock %}
{% block extrahead %}
<style>
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Seguimiento de pedido</h1>
    <h3>Pedido con id: {{ order.id }}</h3>
    <span>Estado del pedido: {{ order.legible_estado }}</span>
</div>

{% endblock %}