motosaurio/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from cart import views as cart_views
from shop import views as shop_views
from motosaurio import urls

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name= 'logout'),
    path('', include('django.contrib.auth.urls')),
    #path('', shop_views.ListProducts.as_view(), name='dashboard'),
    #path('', include('shop.urls', namespace='shop')),
    #path('product/<int:pk>/<slug:slug>/', shop_views.ProductDetailView.as_view(), name='product_detail'),
    path('profile/', views.profile, name='perfil'),
    path('register/', views.register, name='register'),
]

motosaurio/cart/urls.py
from django.urls import path
from . import views
app_name = 'cesta'

urlpatterns = [
 path('', views.cesta_detail, name='cesta_detail'),
 path('add/<int:product_id>/', views.cesta_add, name='cesta_add'),
 path('remove/<int:product_id>/', views.cesta_remove, 
 name='cesta_remove'),
]

motosaurio/motosaurio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path('cesta/', include('cart.urls', namespace='cesta')),
    path('reclamaciones/', include('reclamaciones.urls', namespace='reclamaciones')),
    path('empresa/', include('empresa.urls', namespace='empresa')),
    path("order/", include("order.urls", namespace="order")),
    path("shop/", include("shop.urls", namespace="shop"))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

motosaurio/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
 path('', views.CheckoutOrder.as_view(), name='checkout'),
 path('<int:order_id>/stripe', views.StripeCheckout.as_view(), name='stripe_checkout'),
 path('my_orders/', views.ListOrdersUser.as_view(), name="list-orders-user"),
 path('tracking', views.Tracking.as_view(), name = 'tracking'),
 path('tracking/<int:order_id>', views.TrackingShow.as_view(), name='tracking_show')
]

motosaurio/shop/urls.py
from django.urls import path
from .views import ListProducts, ProductDetailView, sold_products_view

app_name = 'shop'

urlpatterns = [
    path('', ListProducts.as_view(), name='dashboard'),
    path('products_sold/', sold_products_view, name='productos_vendidos'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

motosaurio/account/models.py
from django.db import models

motosaurio/account/forms.py
from django import forms
from motosaurio.models import MiUsuario
from django.core.validators import MaxValueValidator, MinValueValidator

class LoginForm(forms.Form):
    username = forms.CharField(label='Nombre de usuario')
    password = forms.CharField(label='Contraseña',widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    tipos_pago = [
        ["Cr", "Contrareembolso"],
        ["T", "Tarjeta"]
    ]

    tipos_envio = [
        ["D", "A domicilio"],
        ["R", "Recoger en tienda"]
    ]
    password = forms.CharField(label='Contraseña',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repite la contraseña',
                                widget=forms.PasswordInput)
    tarjeta = forms.IntegerField(label='Tarjeta de crédito', required=False)
    payment_type = forms.ChoiceField(label='Método de pago',choices = tipos_pago, initial='T', required=False)
    delivery_type = forms.ChoiceField(label='Método de envío',choices = tipos_envio, initial = "D")

    class Meta:
        model = MiUsuario
        fields = ['username', 'first_name', 'email', 'direccion','codigo','payment_type','delivery_type']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return cd['password2']
    
class UserProfileForm(forms.ModelForm):
    tipos_pago = [
        ["Cr", "Contrareembolso"],
        ["T", "Tarjeta"]
    ]

    tipos_envio = [
        ["D", "A domicilio"],
        ["R", "Recoger en tienda"]
    ]
    tarjeta = forms.IntegerField(label='Tarjeta de crédito', required=False)
    direccion = forms.CharField(label='Dirección postal', required=False)
    codigo = forms.IntegerField(label='Código postal',validators=[MaxValueValidator(99999),MinValueValidator(00000)], required=False)
    payment_type = forms.ChoiceField(label='Método de pago',choices = tipos_pago, initial='T',required=False)
    delivery_type = forms.ChoiceField(label='Método de envío',choices = tipos_envio, initial = "D",required=False)
    class Meta:
        model = MiUsuario
        fields = ['direccion','codigo','tarjeta','payment_type','delivery_type']

    def codigo_invalido(self):
        cd = self.cleaned_data
        if cd['codigo'] == None:
            raise forms.ValidationError('El código postal es obligatorio')
        return cd['codigo']

    def direccion_invalida(self):
        cd = self.cleaned_data
        if cd['direccion'] == '':
            raise forms.ValidationError('La dirección es obligatoria')
        return cd['direccion']

motosaurio/account/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, UserRegistrationForm, UserProfileForm
from motosaurio.models import MiUsuario
from django import forms

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()  
    return render(request, 'account/login.html', {'form': form})

#@login_required
#def dashboard(request):
    #return render(request, 'account/dashboard.html',{'section':'dashboard'})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            return render(request,
                        'account/register_done.html',
                        {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                'account/register.html',
                {'user_form': user_form})

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user)
        try:
            if form.is_valid():
                user = request.user
                user.direccion =form.direccion_invalida()
                user.codigo =form.codigo_invalido()
                user.save()
                return render(request,
                            'account/profile_updated.html', 
                            {'user': request.user}) 
        except forms.ValidationError as e:
            error_message = 'Tanto la dirección como el código postal deben estar cumplimentados'
            return render(request, 'account/error.html', {'error_message': error_message}) 
    else:
        form = UserProfileForm(instance=request.user)

    return render(request, 'account/profile.html', {'form': form})

motosaurio/account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    <style>
        /* Estilos específicos para el menú */
        .menu li {
            font-size: 30px;
            margin-right: 30px;
        }

        /* Otros estilos según sea necesario */
        .cart {
            font-size: 16px;
        }
    </style>

    {% block extrahead %}
    {% endblock %}
</head>

<body>
    <div id="header">
        
        <span class="logo"><img src="{% static 'images/Logo.png' %}" alt="Logo"></span>
        <style>
            .menu li {
                font-size: 30px; 
            }
        </style>
  
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url 'shop:dashboard' %}">Catálogo</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="../../cesta">Carrito</a>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            
                            <a href="{% url "cesta:cesta_detail" %}">
                                {{ total_items }} item{{ total_items|pluralize }},
                                ${{ cart.get_total_price }}
                            </a>
                        {% else %}
                        
                        {% endif %}
                    {% endwith %}
                </div>
            </li>
            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="{% url 'perfil' %}">Perfil</a>
            </li>
            <li {% if section == "empresa" %}class="selected"{% endif %}>
                <a href="../../empresa">Empresa</a>
            </li>
            <li {% if section == "reclamaciones" %}class="selected"{% endif %}>
                <a href="../../reclamaciones">Reclamaciones</a>
            </li>
            {%if user.is_superuser %}
            <li {% if section == "productos vendidos" %}class="selected"{% endif %}>
                <a href="{% url 'shop:productos_vendidos' %}">Productos vendidos</a>
            </li>
            {% endif %}
            <li {% if section == "tracking" %}class="selected"{% endif %}>
                <a href="{% url 'order:tracking' %}">Seguimiento</a>
            </li>
            <li {% if section == "orders" %}class="selected"{% endif %}>
                <a href="{% url 'order:list-orders-user' %}">Mis pedidos</a>
            </li>
            
        </ul>
       
        <style>

            .user {
                font-size: 20px; 
            }
        </style>

        <span class="user">
            
            {% if request.user.is_authenticated %}
                Hola {{ request.user.first_name|default:request.user.username }},
                <a href="{% url "logout" %}">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
            
        </span>
        
    </div>

    {% block content %}
    {% endblock %}

</body>

</html>